
CATEGORY_RULES = {
    "Receptor Targeted": [
        "receptor agonist",
        "receptor antagonist",
        "receptor modulator",
        "receptor inverse agonist",
        "receptor partial agonist",
        "positive allosteric modulator",
        "negative allosteric modulator",
        "allosteric antagonist",
    ],

    "Ion Channels & Transporters": [
        "channel blocker",
        "channel opener",
        "transporter inhibitor",
        "transporter substrate",
        "transporter releasing agent",
        "cotransporter inhibitor",
        "ATPase inhibitor",
        "ENaC blocker",
        "voltage-gated",
        "potassium channel",
        "sodium channel",
        "calcium channel",
    ],

    "Enzymes": [
        "enzyme inhibitor",
        "reductase inhibitor",
        "synthetase inhibitor",
        "synthase inhibitor",
        "hydroxylase inhibitor",
        "dehydrogenase inhibitor",
        "oxidase inhibitor",
        "polymerase inhibitor",
        "protease inhibitor",
        "phosphodiesterase",
        "cyclooxygenase",
        "lipoxygenase",
        "acetylcholinesterase",
        "monoamine oxidase",
        "topoisomerase",
        "kinase inhibitor",
        "transferase inhibitor",
        "farnesyltransferase inhibitor",
    ],

    "Kinases & Signaling": [
        "JAK",
        "RAF",
        "AKT",
        "FLT3",
        "BTK",
        "SYK",
        "SRC",
        "ABL",
        "PI3-kinase",
        "protein kinase",
        "growth factor receptor inhibitor",
    ],

    "Nuclear Receptors & Hormonal": [
        "estrogen receptor",
        "androgen receptor",
        "progesterone receptor",
        "glucocorticoid receptor",
        "mineralocorticoid receptor",
        "thyroid hormone receptor",
        "vitamin D receptor",
        "retinoic acid receptor",
        "retinoid receptor",
        "FXR agonist",
        "PPAR",
    ],

    "Antibacterial / Antifungal": [
        "penicillin-binding protein",
        "beta-lactamase",
        "DNA gyrase",
        "topoisomerase IV",
        "70S ribosome",
        "80S Ribosome",
        "cell wall",
        "bacterial",
        "lanosterol",
        "ergosterol",
        "dihydrofolate reductase",
        "dihydropteroate",
        "RNA polymerase inhibitor",
    ],

    "Antiviral": [
        "human immunodeficiency virus",
        "hepatitis C virus",
        "neuraminidase inhibitor",
        "reverse transcriptase",
        "integrase inhibitor",
        "DNA polymerase inhibitor",
        "RNA-directed RNA polymerase",
        "nonstructural protein",
        "envelope glycoprotein",
        "polymerase acidic protein",
        "DNA terminase",
    ],

    "Oncology / Cytotoxic": [
        "cytotoxic",
        "DNA disrupting agent",
        "tubulin inhibitor",
        "proteasome inhibitor",
        "PARP",
        "EZH2 inhibitor",
        "Bcl-2 inhibitor",
        "CDK",
        "exportin-1 inhibitor",
    ],

    "Neuropharmacology": [
        "dopamine",
        "serotonin",
        "GABA",
        "opioid",
        "adrenergic",
        "acetylcholine",
        "muscarinic",
        "nicotinic",
        "glutamate",
        "NMDA",
        "glycine receptor",
        "melatonin receptor",
        "neurokinin",
    ],

    "Cardiovascular & Renal": [
        "angiotensin",
        "renin inhibitor",
        "endothelin",
        "thrombin inhibitor",
        "factor X inhibitor",
        "P2Y12",
        "vasopressin",
        "guanylate cyclase",
        "prostanoid",
    ],

    "Metabolic & Endocrine": [
        "SGLT",
        "sodium/glucose cotransporter",
        "DPP",
        "sulfonylurea",
        "lipase inhibitor",
        "cholesterol",
        "HMG-CoA",
        "thyroid",
        "glucose",
    ],

    "Chelators / Supplements / Supportive": [
        "chelating agent",
        "supplement",
        "antioxidant",
        "surfactant",
        "excipient",
        "laxative",
        "osmotic agent",
        "diagnostic",
        "diagnostic agent",
        "reducing agent",
    ]
}
